apiVersion: v1
kind: ImageStream
metadata:
  labels:
    role: jenkins-slave
  name: golang
spec:
  tags:
  - from:
      kind: DockerImage
      name: docker.io/bejens/jenkins-slave-go:release-1.12.7
    name: 1.12.7
